/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.AccountDAO;
import DAO.ErrorDataHandling;
import DAO.SQLServerProvider;
import POJO.Account;
import javax.swing.JOptionPane;

/**
 *
 * @author hoant
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfAnswerFP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnBackFP = new javax.swing.JButton();
        jbtSearchFP = new javax.swing.JButton();
        jtfNameFP = new javax.swing.JTextField();
        jcbQuestionFP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfPasswordFP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnChangeFP = new javax.swing.JButton();
        jtfUsernameFP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true), "Forgot Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel1.setText("Username");

        jLabel4.setText("Answer");

        jLabel5.setText("New Password");

        jbtnBackFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Images/goback.png"))); // NOI18N
        jbtnBackFP.setText("Back");
        jbtnBackFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackFPActionPerformed(evt);
            }
        });

        jbtSearchFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Images/find.png"))); // NOI18N
        jbtSearchFP.setText("Search");
        jbtSearchFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchFPActionPerformed(evt);
            }
        });

        jcbQuestionFP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thú Nuôi Đầu Tiên Của Bạn ?", "Quê Hương Của Bạn ?", "Sinh Nhật Của Bạn ?", "Tên Người Yêu Của Bạn ?" }));

        jLabel3.setText("Your Security Question");

        jtfPasswordFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordFPActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jbtnChangeFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Images/changePass.png"))); // NOI18N
        jbtnChangeFP.setText("Change");
        jbtnChangeFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeFPActionPerformed(evt);
            }
        });

        jtfUsernameFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameFPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfUsernameFP)
                    .addComponent(jtfNameFP)
                    .addComponent(jtfAnswerFP)
                    .addComponent(jtfPasswordFP)
                    .addComponent(jcbQuestionFP, 0, 153, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnBackFP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnChangeFP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtSearchFP))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfUsernameFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNameFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbtSearchFP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbQuestionFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfAnswerFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnChangeFP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPasswordFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBackFP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsernameFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameFPActionPerformed

    private void jbtnBackFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackFPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbtnBackFPActionPerformed

    private void jbtnChangeFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeFPActionPerformed
        // TODO add your handling code here:
        try{
             Account searchResult = new Account();
             searchResult = AccountDAO.searchAccountByUserName(this.jtfUsernameFP.getText());
             if(searchResult != null)
             {
                 System.out.println((int)this.jcbQuestionFP.getSelectedIndex()== (int)searchResult.getSecQuestion());
                 System.out.println((String)this.jtfAnswerFP.getText() == (String)searchResult.getAnswer());
                 if((int)this.jcbQuestionFP.getSelectedIndex() == (int)searchResult.getSecQuestion() && this.jtfAnswerFP.getText().equalsIgnoreCase((String)searchResult.getAnswer()) )
                 {
                     if(ErrorDataHandling.isPassword(this.jtfPasswordFP.getText()))
                     {
                        AccountDAO acc = new AccountDAO();
                        acc.changePassword(this.jtfPasswordFP.getText(),this.jtfUsernameFP.getText());
                        JOptionPane.showMessageDialog(null, "Password was changed");
                     }
                     else
                         throw new Exception("Password must have : digit, lowercase, uppercase, punctuation, symbol");
                 }
                 else
                     throw new Exception("Answer incorrect");
             }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnChangeFPActionPerformed

    private void jtfPasswordFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordFPActionPerformed

    private void jbtSearchFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchFPActionPerformed
        // TODO add your handling code here:
         try{
             Account searchResult = new Account();
             searchResult = AccountDAO.searchAccountByUserName(this.jtfUsernameFP.getText());
             if(searchResult != null)
                 this.jtfNameFP.setText(searchResult.getName());
             else
             {
                 JOptionPane.showMessageDialog(this.jtfUsernameFP,"Incorrect User Name");
             }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtSearchFPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtSearchFP;
    private javax.swing.JButton jbtnBackFP;
    private javax.swing.JButton jbtnChangeFP;
    private javax.swing.JComboBox<String> jcbQuestionFP;
    private javax.swing.JTextField jtfAnswerFP;
    private javax.swing.JTextField jtfNameFP;
    private javax.swing.JTextField jtfPasswordFP;
    private javax.swing.JTextField jtfUsernameFP;
    // End of variables declaration//GEN-END:variables
}
